version: "3.7"

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=1
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data
      - ./elasticsearch/var/:/var/lib/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:${VERSION}
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - 12201:12201/udp
      - 5044:5044
    networks:
      - elk

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${VERSION}
    depends_on:
      - logstash
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk

networks:
  elk:
    driver: bridge
